language: python

# Test with python version 2.7
python:
  - "2.7"

# Uncomment the following line to allow dependencies to be installed
# install: "pip install -r requirements.txt"

# command to run tests
script: python mysite/manage.py test socknet

# Slack integration
notifications:
  slack: cmput404team4:HT0av7nWQe41caTypBBG2ht4
    
  
