language: python

# Test with python version 2.7
python:
  - "2.7"

# Uncomment the following line to allow dependencies to be installed
# install: "pip install -r requirements.txt"

services:
  - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python mysite/manage.py migrate

# command to run tests
script: python mysite/manage.py test socknet

# Slack integration
notifications:
  slack: cmput404team4:HT0av7nWQe41caTypBBG2ht4
