# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
