# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserv',
            name='image',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='imglink',
            field=models.UUIDField(null=True),
        ),
    ]
