# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0002_auto_20161120_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserv',
            name='imagetype',
            field=models.CharField(default='.jpg', max_length=12),
            preserve_default=False,
        ),
    ]
