# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0002_auto_20161008_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=512),
        ),
    ]
