# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0003_auto_20161009_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=512),
        ),
    ]
