# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0004_auto_20161121_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
