# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0004_auto_20161009_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=512),
        ),
    ]
