# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0004_auto_20161103_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default=b'No description provided.', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'No Title', max_length=64),
        ),
    ]
