# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0005_auto_20161122_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(default=b''),
        ),
    ]
