# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0006_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
