# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0006_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_node', to='socknet.Node')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='foreign_friends',
            field=models.ManyToManyField(blank=True, related_name='my_foreign_friends', to='socknet.ForeignAuthor'),
        ),
        migrations.AddField(
            model_name='author',
            name='pending_foreign_friends',
            field=models.ManyToManyField(blank=True, related_name='my_pending_foreign_friend_requests', to='socknet.ForeignAuthor'),
        ),
    ]
