# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0007_auto_20161114_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignauthor',
            name='display_name',
        ),
    ]
