# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0007_auto_20161015_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(related_name='my_followers', to='socknet.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(related_name='_author_friends_+', to='socknet.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
