# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0008_foreigncomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigncomment',
            old_name='id',
            new_name='guid',
        ),
    ]
