# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0008_remove_foreignauthor_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignauthor',
            name='display_name',
            field=models.CharField(default=b'test', max_length=150),
        ),
    ]
