# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0008_auto_20161015_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ignore',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to='socknet.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower_of', to='socknet.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='socknet.Author'),
        ),
    ]
