# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0009_auto_20161129_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreigncomment',
            old_name='foreign_author',
            new_name='author',
        ),
    ]
