# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0009_auto_20161016_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ignore',
            new_name='ignored',
        ),
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
        migrations.AddField(
            model_name='author',
            name='who_im_following',
            field=models.ManyToManyField(blank=True, related_name='my_followers', to='socknet.Author'),
        ),
    ]
