# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0010_comment'),
        ('socknet', '0010_auto_20161019_1703'),
    ]

    operations = [
    ]
