# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0010_auto_20161118_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
