# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0010_auto_20161129_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignauthor',
            old_name='id',
            new_name='uuid',
        ),
    ]
