# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0010_auto_20161120_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
