# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0011_auto_20161129_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignauthor',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='foreigncomment',
            old_name='author',
            new_name='foreign_author',
        ),
    ]
