# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0011_merge_20161020_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_post',
        ),
    ]
