# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0011_node_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
    ]
