# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0011_auto_20161119_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('sharePosts', models.BooleanField(default=True)),
                ('shareImages', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin Configuration',
                'verbose_name_plural': 'Admin Configuration',
            },
        ),
    ]
