# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0011_auto_20161120_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, default=b'N/A', max_length=64),
        ),
    ]
