# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0013_auto_20161119_2211'),
        ('socknet', '0013_node_user'),
    ]

    operations = [
    ]
