# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0014_auto_20161022_0015'),
        ('socknet', '0014_image'),
    ]

    operations = [
    ]
