# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0014_merge_20161119_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfig',
            name='shareImages',
            field=models.BooleanField(default=True, verbose_name=b'Share Images with Other Nodes'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='sharePosts',
            field=models.BooleanField(default=True, verbose_name=b'Share Posts with Other Nodes'),
        ),
    ]
