# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0015_auto_20161119_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='foreignNodePass',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='foreignNodeUser',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
