# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0016_auto_20161022_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserv',
            name='image',
            field=models.ImageField(upload_to=b'user_images'),
        ),
    ]
