# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0017_auto_20161022_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserv',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
