# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0018_auto_20161022_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imguuid',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
