# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0019_post_imguuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imguuid',
        ),
        migrations.AddField(
            model_name='post',
            name='imglink',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageserv',
            name='image',
            field=models.ImageField(max_length=256, upload_to=b'user_images'),
        ),
    ]
