# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socknet', '0020_auto_20161022_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserv',
            name='parent_post',
            field=models.ForeignKey(default='9ecaefe701ce489993a915afa5b1ef15', on_delete=django.db.models.deletion.CASCADE, related_name='image_parent_post', to='socknet.Post'),
            preserve_default=False,
        ),
    ]
